### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by pawamoy** [tanbro/mkdocs-nbconvert#2]
Hi, could you add a LICENSE file to your repository? It would help to improve https://github.com/pawamoy/best-of-mkdocs contents :slightly_smiling_face: 
If this project is unmaintained, just let me know :+1:

**Comment by tanbro** [comment]
Thanks for your notice!

The project is still under maintainment, and I'll add a licence file later.

**Comment by pawamoy** [comment]
Thanks! I see you added BSD 2-Clause as LICENSE file, but BSD 3-Clause in setup.cfg, is that normal? I have no knowledge in BSD licenses, just asking out of curiosity :slightly_smiling_face: Anyway, the best-of list generator will be able to detect the license now, thanks again and closing :slightly_smiling_face:

**Comment by tanbro** [comment]
Oh, that's a careless mistake ... i'll fix it later.
